project-key: MIN

name: minerva

parameters:
  data_dir: /mnt/ml-team/minerva/whales/data
  solution_dir: /mnt/ml-team/minerva/cache/whales/solution/alignment

exclude:
  - output
  - neptune.log
  - offline_job.log
